name: Bug 反馈
description: 反馈您遇到的 Bug
title: [Bug] (您对此 Bug 的简短描述)
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        请认真并详细地填写 Issue 表单，以便开发者更好地解决问题。
  - type: checkboxes
    attributes:
      label: 请先确认以下几件事
      options:
        - label: 更新到 Release 中的最新版本，有些 Bug 可能已在新版中修复
          required: true
        - label: 查看过 README 中的常见问题，并且尝试解决过
          required: true
  - type: textarea
    attributes:
      label: 您遇到的问题
      description: 详细描述您遇到的 Bug，它出现了怎样的行为，以及您期望的行为
    validations:
      required: true
  - type: textarea
    attributes:
      label: 重现步骤
      description: 详细描述要如何触发这个 Bug
      placeholder: |
        1. ……
        2. ……
        3. ……
    validations:
      required: true
  - type: textarea
    attributes:
      label: 日志
      description: 请贴出遇到 Bug 时程序的报错日志
      render: shell
    validations:
      required: true
  - type: input
    attributes:
      label: 插件版本
      description: 写出您正在使用的插件版本
      placeholder: 如：1.3.0
    validations:
      required: true
  - type: input
    attributes:
      label: ClassIsland 版本
      description: 写出您正在使用的 ClassIsland 版本
      placeholder: 如：1.7.0.0
  - type: dropdown
    attributes:
      label: 操作系统
      description: 您的操作系统（版本）
      options:
        - Windows 11
        - Windows 10
        - Linux（？）
        - 其他
      default: 0
